# Site settings
title: Blog of Alan Pies
email: alan.lee.pies@gmail.com
description: "A Blog about coding, politics, and time travel to the 90s"
baseurl: ""
url: "http://apies.github.io"
twitter_username: AlanPies
github_username:  apies

# Build settings
markdown: kramdown
permalink: pretty
